### ISSUE TITLE
Warning: ray.rb:2:in `<top (required)>': iconv will be deprecated

### ISSUE THREAD

**Issue by sadfuzzy** [Mon-Ouie/ray#58]
```
../vendor/bundle/gems/ray-0.2.0/lib/ray/ray.rb:2:in `<top (required)>': iconv will be deprecated in the future, use String#encode instead.
```

**Comment by kyrylo** [comment]
https://github.com/Mon-Ouie/ray/issues/54

**Comment by sadfuzzy** [comment]
Thanks!
